### PR TITLE
Add Fastspeech2 and Tacotron2

### PR DESCRIPTION
**Pull request by Masao-Someki**
This PR adds fastspeech2 and tacotron2 models.
- [x] FastSpeech2
- [x] Tacotron2

### CODE REVIEW

**Comment by Masao-Someki** [comment]
## Performance check for FastSpeech2 with HifiGAN
I used the model named `kan-bayashi/ljspeech_tts_train_joint_conformer_fastspeech2_hifigan_raw_phn_tacotron_g2p_en_no_space_train.total_count.ave`.
Every inference was executed on my CPU.
I generated a wav file for 'Hello world!' for the test.

- torch: 0.19996 sec
- onnx (without quantize): 0.17593 sec
- onnx (quantize only matmul): 0.17307 sec

**Comment by Masao-Someki** [comment]
I think there are some bugs in the code... the result of tacotron2 is different from the original torch model.
The inference for the `prob` was not going well, so the length of the output feature is longer in onnx output.

| onnx | torch |
| --- | --- |
|Figure_1 |Figure_2 |

**Comment by Masao-Someki** [comment]
## Performance check for Tacotron2
I used the model named `kan-bayashi/ljspeech_tacotron2`.
All inference is executed on my CPU.
I generated a wav file for 'Hello world!' for the test.

- torch: 0.44108 sec
- onnx (without quantize): 0.25100 sec
- onnx (quantize only matmul): 0.09711 sec

**Comment by sciai-ai** [comment]
> 'Hello world!'

@Masao-Someki 

Can you share the code for reproducing these timings. Thanks

**Comment by Masao-Someki** [comment]
@sciai-ai 
Here is the snippet.
Note that the device is CPU, and the first call of `onnx_model(text)` takes a long time.

```python
# load torch and onnx model
tag_name = 'kan-bayashi/ljspeech_tacotron2'
text = 'Hello world!'

from espnet2.bin.tts_inference import Text2Speech as espnetTTS
from espnet_onnx import Text2Speech as onnxTTS

torch_model = espnetTTS.from_pretrained(tag_name)
onnx_model = onnxTTS(tag_name, use_quantized=False)

# utility function
import time
def run(t):
    def _deco_tag(func):
        def wrapper(*args, **kwargs):
            start_time = time.time()
            for _ in range(t):
                func(*args, **kwargs)
            end_time = time.time()
            print('mean elapsed time: %.5f' % ((end_time - start_time)/t))
            print('sum elapsed time: %.5f' % ((end_time - start_time)))
        return wrapper
    return _deco_tag

@run(50)
def run_torch(text):
  out = torch_model(text)

@run(50)
def run_onnx(text):
  out = onnx_model(text)

# check inference time
run_torch(text)
# mean elapsed time: 0.41712
# sum elapsed time: 20.85600

run_onnx(text)
# mean elapsed time: 0.22997
# sum elapsed time: 11.49867
```

**Comment by shakhbozabdigapporov** [comment]
can you share the source code for converting the tacotron2 tts pytorch model to onnx ? I have trained my custom data but having a hard time to convert my model into onnx

**Comment by shakhbozabdigapporov** [comment]
> these
I am trying to convert my trained pytorch model to onnx. But I am facing the same problem(that the generated sound from the onnx model is not good). Any updates on this issue ? 
My model is trained with tacotron2

**Pull request merged**
