### PR TITLE
Feature/transducer

### PR DESCRIPTION
**Pull request by Masao-Someki**
Add support for the transducer model.

- support JointNetwork
- support TransducerDecoder
- support beam_search_transducer

### CODE REVIEW

**Comment by Masao-Someki** [comment]
## Speed check
I used 6.6 sec wav file with `espnet/chai_librispeech_asr_train_conformer-rnn_transducer_raw_en_bpe5000_sp` model.
All inference is executed on the CPU.
`beam_size` is 20, except for the greedy search.

```
transducer_config = {
	'search_type': '<algorithm>',
	'max_sym_exp': 4,
	'u_max': 100,
	'nstep': 3,
	'prefix_alpha': 3,
	'expansion_gamma': 1.3,
	'expansion_beta': 1,
	'score_norm': True
}
```

**greedy**
- torch: 0.34939
- onnx(without quantize): 0.23055

**default**
- torch: 4.01989
- onnx(without quantize): 2.70313

**tsd**
- torch: 4.57367
- onnx(without quantize): 8.52332

**alsd**
- torch: 2.05102
- onnx(without quantize): 2.79953

**nsc**
- torch: 5.05434
- onnx(without quantize): 7.90546

**maes**
- torch: 17.34415
- onnx(without quantize): 3.73707

**Comment by Masao-Someki** [comment]
The performance issue with some search algorithms is caused by the `topk` method. So I applied `bottleneck.argpartition` as the backend of the topk method. The result may not be sorted, but there is no problem with inference.

## Speed check
I used the same configuration as above.

**greedy**
- torch: 0.47540 sec
- onnx(without quantize): 0.25496 sec

**default**
- torch: 3.90362 sec
- onnx(without quantize): 1.42983 sec

**tsd**
- torch: 4.67816 sec
- onnx(without quantize): 3.15475 sec

**alsd**
- torch: 2.05233 sec
- onnx(without quantize): 1.34215 sec

**nsc**
- torch: 5.04234 sec
- onnx(without quantize): 4.03658

**maes**
- torch: 19.64574 sec
- onnx(without quantize): 3.87056 sec

**Comment by Masao-Someki** [comment]
With the modification of the `topk`, the inference speed of the other models also improved.
For example, using the `StreamingSpeech2Text` with D-keqi's model for the 6.6 sec wav file, I got 2.83040 second for inference, which is about 0.4~0.5 seconds faster than the previous implementation.

**Comment by b-flo** [comment]
Hi @Masao-Someki,

Thanks a lot for this PR!

> The performance issue with some search algorithms is caused by the topk method. So I applied bottleneck.argpartition as the backend of the topk method. The result may not be sorted, but there is no problem with inference.

Could you explain a bit more, please? Are you talking about the bug in mAES (which is not fixed in master for this version yet) or there is an issue related to `topk(...)` in ONNX?

Btw, given the model, `beam-size: 10` is sufficient and the following config would give about the same results (can be further tuned I guess):

```
transducer_config = {
	'search_type': '<algorithm>',
	'max_sym_exp': 3,
	'u_max': 50,
	'nstep': 2,
	'prefix_alpha': 1,
	'expansion_gamma': 0.9,
	'expansion_beta': 0,
	'score_norm': True
}
```

In terms of ER/RTF, the ranking should look like this (outside some edge cases): greedy < mAES < ALSD < TSD

**Comment by Masao-Someki** [comment]
Hi @b-flo,
> Could you explain a bit more, please? Are you talking about the bug in mAES (which is not fixed in master for this version yet) or there is an issue related to topk(...) in ONNX?

I implemented my own `topk` in `espnet_onnx.utils.function`. In the previous implementation, I used the `argsort` for topk, and this was too slow...
https://github.com/Masao-Someki/espnet_onnx/blob/265d59e378877eb3b90112337e7d11567a74dd0d/espnet_onnx/utils/function.py#L135-L158

Thank you for the transducer configuration!
 I just wanted to check if the inference speed would improve between the torch and the onnx in the same config, but next time I will tune it for speed check!

**Comment by b-flo** [comment]
> I implemented my own topk in the espnet_onnx.utils.function since beam_search algorithms will not be converted. In the previous implementation, I used the argsort for topk, and this was too slow...
> ...

Thanks a lot for the explanations! I'll do some testing myself, I think `argmax` should be faster for top-1 and arranging + percentiles should give the same complexity on most cases, what do you think?
Also, it seems `partition` and `argpartition` are available in numpy 1.8+, I think it can be a requirement?

**Comment by Masao-Someki** [comment]
Sorry, I don't have some images for the implementation of arranging + percentile, but I think `argmax` is faster for the top-1 case.
As for `partition` and `argpartition`, these should be faster than `argsort`.  But if you could use the `torch.topk`, then I don't think there is too much difference. 
Note that time complexity for `torch.topk` is `O(n+k)` as investigated [here](https://discuss.pytorch.org/t/whats-the-time-complexity-of-tensor-topk/117856/3), and for `partition` and `argpartition` is `O(n)` on average.

I chose `bottleneck` because we cannot use `torch` in espnet_onnx, and it seems it's faster than NumPy.

**Comment by b-flo** [comment]
>As for partition and argpartition, these should be faster than argsort. But if you could use the torch.topk, then I don't think there is too much difference.
> Note that time complexity for torch.topk is O(n+k) as investigated [here](https://discuss.pytorch.org/t/whats-the-time-complexity-of-tensor-topk/117856/3), and for partition and argpartition is O(n) on average.

Yes, that's what I read, thanks for the link!

> I chose bottleneck because we cannot use torch in espnet_onnx, and it seems it's faster than NumPy.

>Edit
> I tested the performance and it seems np.partition is faster than bottleneck.partition... I will fix it in the next PR.

From what I seen, speed where about the same but glad it's faster with `np`! I was just asking about the package dependence and if it could be avoided :)

**Pull request merged**
